### PR TITLE
Update publish.yml

### PR DESCRIPTION
**Pull request by khammami**

### CODE REVIEW

**Comment by beniroquai** [comment]
Hey @khammami many thanks for helping me with the action. I did a hacky workaround with a find/replace action. What do you think is more appropriate? 
Also do you have a guess when Google will discontinue codelabs? ;-)

**Comment by khammami** [comment]
@beniroquai both works, but you may test both and see which one take less time.

this tools started by Google and now maintained by the community. lately Google has made some clean up and they deleted some files by mistake, so to to avoid this kind of issue in the future. it would better to host them and use our own links :)

**Comment by beniroquai** [comment]
Thanks a lot for your advice! Would it still be possible to build the
codelabs with go/claat if google decides to discontinue it? Wouldn't be the
first time that Google discontinues a great open source project.. ;-)

I'll compare your solution with the quick and dirty one ;-)

**Comment by khammami** [comment]
Yes I got your point. But I told this tools is maintained mostly by the community. Even they did, you can compile your own claat from source code like I did. I'm using a custom claat that I modified since a year now. So don't worry and keep making labs ;)

**Comment by beniroquai** [comment]
Great! thanks for your help! Very much appreciated :-)

**Pull request closed without merging**
